import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link';
import Widget from './partials/widget';

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <>
      {/*[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]*/}
      {/*[if (gte IE 9)|!(IE)]><!*/} {/*<![endif]*/}
      {/* Basic Page Needs */}
      <meta charSet="utf-8" />
      <title>Work Scout</title>
      {/* Mobile Specific Metas */}
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1"
      />
      {/* CSS */}
      <link rel="stylesheet" href="/css/style.css" />
      <link rel="stylesheet" href="/css/colors/green.css" id="colors" />
      {/*[if lt IE 9]>
	
<![endif]*/}
      <div id="wrapper">
        {/* Header */}
        <header>
          <div className="container">
            <div className="sixteen columns">
              {/* Logo */}
              <div id="logo">
                <h1>
                  <a href="/">
                    <img src="/images/logo.png" alt="Work Scout" />
                  </a>
                </h1>
              </div>
              {/* Menu */}
              <nav id="navigation" className="menu">
                <ul id="responsive">
                  <li>
                    <Link href="https://meitech-ekabintan.com">Home</Link>
                  </li>
                  <li>
                    <a href="#" id="current">
                      For Candidates
                    </a>
                    <ul>
                      <li>
                        <a href="browse-jobs.html">Browse Jobs</a>
                      </li>
                      <li>
                        <a href="browse-categories.html">Browse Categories</a>
                      </li>
                      <li>
                        <a href="add-resume.html">Add Resume</a>
                      </li>
                      <li>
                        <a href="manage-resumes.html">Manage Resumes</a>
                      </li>
                      <li>
                        <a href="job-alerts.html">Job Alerts</a>
                      </li>
                    </ul>
                  </li>
                </ul>
                <ul className="responsive float-right">
                  <li>
                    <a href="my-account.html#tab2">
                      <i className="fa fa-user" /> Sign Up
                    </a>
                  </li>
                  <li>
                    <a href="my-account.html">
                      <i className="fa fa-lock" /> Log In
                    </a>
                  </li>
                </ul>
              </nav>
              {/* Navigation */}
              <div id="mobile-navigation">
                <a href="#menu" className="menu-trigger">
                  <i className="fa fa-reorder" /> Menu
                </a>
              </div>
            </div>
          </div>
        </header>
        <div className="clearfix" />
        {/* Titlebar */}
        <div id="titlebar">
          <div className="container">
            <div className="ten columns">
              <span>We found 1,412 jobs matching:</span>
              <h2>Web, Software &amp; IT</h2>
            </div>
            <div className="six columns">
              <a href="add-job.html" className="button">
                Post a Job, It’s Free!
              </a>
            </div>
          </div>
        </div>
        {/* Content */}
        <div className="container">
          {children}
        </div>
        {/* Footer */}
        <div className="margin-top-25" />
        <div id="footer">
          {/* Main */}
          <div className="container">
            <div className="seven columns">
              <h4>About</h4>
              <p>
                Morbi convallis bibendum urna ut viverra. Maecenas quis
                consequat libero, a feugiat eros. Nunc ut lacinia tortor morbi
                ultricies laoreet ullamcorper phasellus semper.
              </p>
              <a href="#" className="button">
                Get Started
              </a>
            </div>
            <div className="three columns">
              <h4>Company</h4>
              <ul className="footer-links">
                <li>
                  <a href="#">About Us</a>
                </li>
                <li>
                  <a href="#">Careers</a>
                </li>
                <li>
                  <a href="#">Our Blog</a>
                </li>
                <li>
                  <a href="#">Terms of Service</a>
                </li>
                <li>
                  <a href="#">Privacy Policy</a>
                </li>
                <li>
                  <a href="#">Hiring Hub</a>
                </li>
              </ul>
            </div>
            <div className="three columns">
              <h4>Press</h4>
              <ul className="footer-links">
                <li>
                  <a href="#">In the News</a>
                </li>
                <li>
                  <a href="#">Press Releases</a>
                </li>
                <li>
                  <a href="#">Awards</a>
                </li>
                <li>
                  <a href="#">Testimonials</a>
                </li>
                <li>
                  <a href="#">Timeline</a>
                </li>
              </ul>
            </div>
            <div className="three columns">
              <h4>Browse</h4>
              <ul className="footer-links">
                <li>
                  <a href="#">Freelancers by Category</a>
                </li>
                <li>
                  <a href="#">Freelancers in USA</a>
                </li>
                <li>
                  <a href="#">Freelancers in UK</a>
                </li>
                <li>
                  <a href="#">Freelancers in Canada</a>
                </li>
                <li>
                  <a href="#">Freelancers in Australia</a>
                </li>
                <li>
                  <a href="#">Find Jobs</a>
                </li>
              </ul>
            </div>
          </div>
          {/* Bottom */}
          <div className="container">
            <div className="footer-bottom">
              <div className="sixteen columns">
                <h4>Follow Us</h4>
                <ul className="social-icons">
                  <li>
                    <a className="facebook" href="#">
                      <i className="icon-facebook" />
                    </a>
                  </li>
                  <li>
                    <a className="twitter" href="#">
                      <i className="icon-twitter" />
                    </a>
                  </li>
                  <li>
                    <a className="gplus" href="#">
                      <i className="icon-gplus" />
                    </a>
                  </li>
                  <li>
                    <a className="linkedin" href="#">
                      <i className="icon-linkedin" />
                    </a>
                  </li>
                </ul>
                <div className="copyrights">
                  © Copyright 2015 by <a href="#">Work Scout</a>. All Rights
                  Reserved.
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* Back To Top Button */}
        <div id="backtotop">
          <a href="#" />
        </div>
      </div>
      {/* Wrapper / End */}
      {/* Scripts */}
    </>
  );
}
